version: '3'
services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=postgress_password

  nginx:
    depends_on:
      - api
      - frontend
    restart: always
    build: 
      dockerfile: dockerfile.nginx
      context: ./nginx
    ports:
      - '4000:80'

  api:
    build: 
      dockerfile: ./backend/Dockerfile
      context: ./backend
    ports:
      - '4000:4000'
    volumes:
      - ./backend/node-modules:/app/node-modules
      - ./backend:/app
    environment:
      - SUPABASE_KEY_URL=https://rqufzhhcewwjafsuxipv.supabase.co
      - SUPABASE_ACCESS_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxdWZ6aGhjZXd3amFmc3V4aXB2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTA5MjEyODUsImV4cCI6MjAyNjQ5NzI4NX0.zh8JWJmTq9kQxbsBTakBcS2shXgVvOTq6lZV_pUGxu0
      - PORT=4000

  frontend:
    build: 
      dockerfile: ./frontend/Dockerfile
      context: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/node-modules:/app/node-modules
      - ./frontend:/app
